FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y curl apt-transport-https gnupg && \
    curl https://cli-assets.heroku.com/install-ubuntu.sh | sh && \
    apt-get clean

USER jenkins
